In [1]:
import numpy as np

In [2]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)

In [3]:
type(arr)

numpy.ndarray

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
#multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr1=np.array([my_lst1,my_lst2,my_lst3])

In [6]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [7]:
type(arr1)

numpy.ndarray

In [8]:
arr1.shape

(3, 5)

In [9]:
arr.shape

(5,)

In [10]:
arr[3]

4

In [11]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [12]:
arr1.reshape(3,5)

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [13]:
#Indexing
arr1[0:,:2]

array([[1, 2],
       [2, 3],
       [9, 7]])

In [14]:
arr[2]=100

In [15]:
arr

array([  1,   2, 100,   4,   5])

In [16]:
arr[2]=3

In [17]:
arr

array([1, 2, 3, 4, 5])

In [18]:
arr1[arr1<7]

array([1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 6])

In [19]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [20]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
arr1[1:,3:]

array([[5, 6],
       [8, 9]])

In [23]:
a=np.arange(0,10,step=2)

In [24]:
a

array([0, 2, 4, 6, 8])

In [25]:
b=np.linspace(1,50,50)

In [26]:
b

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [29]:
b.astype(int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [30]:
arr<1

array([False, False, False, False, False])

In [45]:
n=5
for x in range (1,n+1):
    print(x, end="")

12345